### ISSUE TITLE
support for current sink on 6632 series

### ISSUE THREAD

**Issue by Harry-ei6ku** [Niravk1997/663x2A-663xB-661xC-System-DC-Power-Supply-Software#2]
This is a nice project, many thanks for making it open source.

The 6632 series can sink current in a controlled manner and so behave like a dummy load, up to its full spec, ie 20v 5A, I'm not sure the software currently takes advantage of this feature?

H

**Comment by Niravk1997** [comment]
The software does support sinking current. I tested it, works nicely. The current will be read as negative just like seen on the front panel's vfd display. The current and power graphs will be negative.
In the below image, I am sourcing current from one power supply and sinking it using another one.
![Sink](https://user-images.githubusercontent.com/52579388/109190792-75fe4d80-7763-11eb-9ae1-d3a8cc56d127.PNG)
![Graphs](https://user-images.githubusercontent.com/52579388/109190837-86aec380-7763-11eb-9857-638428260de4.PNG)

**Comment by Harry-ei6ku** [comment]
Yes I see that now, I'll check it out.
