### ISSUE TITLE
is this a .net assemble?

### ISSUE THREAD

**Issue by Harry-ei6ku** [Niravk1997/663x2A-663xB-661xC-System-DC-Power-Supply-Software#3]
Hello

Is this software a .net assembly?

if yes then I will try to run it under mono on Mac and linux.

**Comment by Niravk1997** [comment]
Hi, 

This software was created using C# WPF .NET framework 4.7.2. I don't think mono supports WPF. You could however run the software on window 7 through virtual machine, I tried that and it worked nicely. Hope that helps.

**Comment by Harry-ei6ku** [comment]
OK thanks yes all understood, again nice project and thanks for publishing it.
